<?php
session_start();
require 'includes/header.php';

require_once 'components/NewsService.php';
$newsService = new NewsService();

if( isset($_GET['id']) AND isset($_GET['delete']) ){
	$newsId = htmlentities($_GET['id']);
	$newsService->deleteNews($newsId);
	$updatedNews['id'] = 0;

}else if(isset($_GET['id']) AND isset($_POST['title'])){

	$updatedNews = array();
	$updatedNews['id'] = htmlentities($_GET['id']);
	$updatedNews['title'] = htmlentities($_POST['title']);
	// summary is generated from the text
	$updatedNews['text'] = htmlentities($_POST['text']);
	// datetime is generated by MySQL on the fly
	$updatedNews['picture'] = htmlentities($_POST['picture']);
	$updatedNews['category'] = htmlentities($_POST['category']);


	$newsService->updateNews($updatedNews);

}

echo '
<div class="hero fullscreen">
            <div class="hero-body">
                <div class="content">


';

	echo '

<div class="toast toast--info">
    <button class="btn-close"></button>
    <p><b>Info:</b> News edited successfully, redirecting...</p>
</div>

';

echo '<meta http-equiv="refresh" content="2;url=newspiece.php?id='.$updatedNews['id'].'" />
<p style="text-align:center">Click <a href="newspiece.php?id='.$updatedNews['id'].'">here</a> if you are not automatically redirected.</p>
				<br><br><br><br>
                </div>
            </div>
        </div>
';

require 'includes/footer.php';
